crsf_joy_drv:
  mapping:
    buttons: [5, 6, 7, -1, 4]
    axis: [2, 1, 0, 3, 5, 6, -1]

  serial:
    port: /dev/serial/by-path/platform-70090000.xusb-usb-0:2.4.4:1.0-port0
    baudrate: 440000

  joy_message_rate: 25

  failsafe:
    timeout: .5
    buttons: [0, 0, 0, 0, 0]
    axis: [0, 0, 0, 0, 0, 0, 0]

  deadband: 0.05