version: "3.6"
services:
  builder:
    extends: &extend
      file: ../docker-compose.yaml
      service: drivers
    image: robot-image
    runtime: nvidia
    restart: "no"
    command: /bin/bash -c "
      ccache -s &&
      source /init_workspaces &&
      cd /ros_melodic_robot/ &&
      ls -al &&
      catkin config -DBUILD_WITH_CUDA=true -DFORCE_RSUSB_BACKEND=true -DCMAKE_BUILD_TYPE=release -DBUILD_WITH_OPENMP=true -DBUILD_EXAMPLES=false -DBUILD_GLSL_EXTENSIONS=false &&

      catkin clean -y &&
      time catkin build --no-status --interleave
      "

