# USB port
serial_port: /dev/serial/by-path/platform-70090000.xusb-usb-0:2.4.2:1.0-port0
# Tf frame id
frame_id: imu_bosch_link
freqency: 100
use_temperature: true
use_magnetometer: true
operation_mode: NDOF
reset_orientation: true
