#!/bin/bash
#if [! -d ./src ] ; then echo "This script needs to be run from the root of your ros workspace"; exit 1; fi
#docker run --net=host --runtime nvidia -it --privileged -v /dev:/dev -v `pwd`:'/ros_melodic_robot' robot-image 