version: "3.6"
services:
  builder:
    extends: &extend
      file: docker-compose.base.yaml
      service: base
    image: robot-builder
    runtime: nvidia

    command: /bin/bash -c "
      ccache -s &&
      export PATH="/usr/lib/ccache:$PATH"
      source /init_workspaces &&
      cd /ros_melodic_robot/ &&
      ls -al &&
      catkin config -DBUILD_WITH_CUDA=true -DFORCE_RSUSB_BACKEND=true -DCMAKE_BUILD_TYPE=release -DBUILD_WITH_OPENMP=true -DBUILD_EXAMPLES=false -DBUILD_GLSL_EXTENSIONS=false &&

      catkin clean -y &&
      time catkin build --no-status --interleave
      "
    

