visual_odometry:
  # Odom:
    # FillInfoData: true
    # ResetCountdown: 1
    # Strategy: 0
  # Vis:
    # FeatureType: 6
    # MaxFeatures: 500

  # OdomF2M:
    # MaxSize: 1000
  # Reg:
    # Force3DoF: false
rtabmap:
  frame_id: "base_link"
  map_frame_id: "map"
  odom_sensor_sync: false
  # wait_for_transform_duration: 0.2
  approx_sync: true

  database_path:      "~/.ros/rtabmap.db"
  #Reg:
  #  Force3DoF: false
  #Grid:
  #    3D:                     false
  #    FlatObstacleDetected:   true
  #     MapFrameProjection:     false
  #     GroundIsObstacle:       false
  #     PreVoxelFiltering:      true
  #     RayTracing:             true
  #     FromDepth:              true
  #    CellSize:               0.01
  #    ClusterRadius:          0.01
  #     MinClusterSize:         3
  #     DepthDecimation:        1
  #     DepthRoiRatios:         [0.0, 0.0, 0.0, 0.0]
  #     FootprintHeight:        0.7
  #     FootprintLength:        0.2
  #     FootprintWidth:         0.2
  #     MaxGroundAngle:         45.0
  #     MinGroundHeight:        0.0
  #     MaxGroundHeight:        0.03
  #     MaxObstacleHeight:      0.8
  #     NoiseFilteringMinNeighbors: 5
  #     NoiseFilteringRadius:   0.0
  #     NormalK:                20
  #     RangeMin:               0.35
  #     RangeMax:               8.0

  # GridGlobal:
  #     Eroded:                 false       # Erode obstacle cells
  #     FootprintRadius:        0.18        # Footprint radius (m) used to clear all obstacles under the graph
  #     FullUpdate:             true        # When the graph is changed, the whole map will be reconstructed instead of moving individually each cells of the map. Also, data added to cache won't be released after updating the map. This process is longer but more robust to drift that would erase some parts of the map when it should not
  #     MaxNodes:               0           # Maximum nodes assembled in the map starting from the last node (0=unlimited)
  #     MinSize:                10.0        # Minimum map size (m)
  #     OccupancyThr:           0.65        # Occupancy threshold (value between 0 and 1)
  #     ProbClampingMax:        0.971       # Probability clamping maximum (value between 0 and 1)
  #     ProbClampingMin:        0.1192      # Probability clamping minimum (value between 0 and 1)
  #     ProbHit:                0.7         # Probability of a hit (value between 0.5 and 1)
  #     ProbMiss:               0.4         # Probability of a miss (value between 0 and 0.5)
  #     UpdateError:            0.01        # Graph changed detection error (m). Update map only if poses in new optimized graph have moved more than this value
